#!/usr/bin/env python


def get_options():
    import argparse

    description = 'Make contigs names shorter'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('input',
                        help='Input fasta file')
    parser.add_argument('output',
                        help='Output fasta file')

    parser.add_argument('--prefix',
                        default='contig',
                        help='New contigs prefix name [Default: contig]')
    
    return parser.parse_args()


if __name__ == "__main__":
    options = get_options()

    from Bio import SeqIO

    seqs = []
    for i, s in enumerate(SeqIO.parse(options.input, 'fasta')):
        s.id = options.prefix + str(i + 1)
        s.description = ''
        seqs.append(s)

    SeqIO.write(seqs, options.output, 'fasta')
