#!/usr/bin/env python


def get_options():
    import argparse

    description = 'Fix tree labels'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('input',
                        help='Input tree in Newick format')
    parser.add_argument('output',
                        help='Output tree in Newick format')

    return parser.parse_args()


if __name__ == "__main__":
    options = get_options()

    from Bio import Phylo

    t = Phylo.read(options.input, 'newick')

    for c in t.get_terminals():
        c.name = c.name.replace('.fasta', '')

    t.root_at_midpoint()

    Phylo.write(t, options.output, 'newick')
