#!/usr/bin/env python


def get_options():
    import argparse

    description = 'Prepare references file for annotating kmers'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('fastas',
                        help='Genomics fasta files directory')
    parser.add_argument('gffs',
                        help='GFFs files directory (structure: directory/X/X.gff)')

    parser.add_argument('--ref',
                        action='append',
                        help='Prefix of reference genome(s)')
    
    return parser.parse_args()


if __name__ == "__main__":
    options = get_options()

    import os

    ref = []
    draft = []
    for g in os.listdir(options.fastas):
        if not g.endswith('.fasta'):
            continue
        prefix = os.path.split(g)[-1].split('.')[0]
        if prefix in options.ref:
            ref.append('\t'.join((os.path.join(options.fastas, g),
                                  os.path.join(options.gffs, prefix, prefix + '.gff'),
                                  'ref')))
        else:
            draft.append('\t'.join((os.path.join(options.fastas, g),
                                    os.path.join(options.gffs, prefix, prefix + '.gff'),
                                    'draft')))
    
    for x in ref:
        print(x)
    for x in draft:
        print(x)
