#!/usr/bin/env python


def get_options():
    import argparse

    description = 'Restrict a similarity matrix to strains w/ gene hits'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('similarity',
                        help='Similarity matrix')
    parser.add_argument('genes',
                        help='Genes count table')
    
    parser.add_argument('--threshold',
                        type=int,
                        default=14,
                        help='Minimum associated genes [Default: 14]')

    return parser.parse_args()


if __name__ == "__main__":
    options = get_options()

    import sys
    import pandas as pd

    p = pd.read_table(options.similarity, index_col=0)
    m = pd.read_table(options.genes,
                      sep=' ',
                      index_col=0,
                      header=None)

    p.loc[m[m > options.threshold].dropna().index,
          m[m > options.threshold].dropna().index].to_csv(sys.stdout,
                                                 sep='\t')
