#!/usr/bin/env python


def get_options():
    import argparse

    description = 'Count associated genes for each sample'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('summary',
                        help='Summary table')
    parser.add_argument('roary',
                        help='Genes presence/absence csv filE')

    return parser.parse_args()


if __name__ == "__main__":
    options = get_options()
    
    import pandas as pd
    
    roary = pd.read_table(options.roary,
                          sep=',',
                          low_memory=False)
    roary.set_index('Gene', inplace=True)
    roary.drop(list(roary.columns[:13]), axis=1, inplace=True)
    
    genes = {}
    for strain in roary.columns:
        genes[strain] = set(roary[strain].dropna().index)

    summary = pd.read_table(options.summary,
                            index_col=0)

    for strain in sorted(roary.columns):
        print(' '.join((strain, str(len(summary.index.intersection(genes[strain]))))))
