#!/usr/bin/env python


def get_options():
    import argparse

    description = 'Copy and unpack genomes (spit out commands)'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('idir',
                        help='Input directory')
    parser.add_argument('odir',
                        help='Output directory')
    
    parser.add_argument('--sample',
                        type=int,
                        default=1,
                        help='How many genomes per directory [Default: 1]')

    return parser.parse_args()


if __name__ == "__main__":
    options = get_options()

    import os
    import random

    i = 1
    for dname, dnames, fnames in os.walk(options.idir):
        fnames = [x for x in fnames
                  if x.endswith('.gz')]
        if len(fnames) == 0:
            continue
        random.shuffle(fnames)
        fnames = fnames[:options.sample]
        for fname in fnames:
            print('cp -L "%s" "%s"' % (os.path.join(dname, fname),
                                       os.path.join(options.odir, 'genome%03d.gz' % i)))
            print('gunzip "%s"' % os.path.join(options.odir,
                                               'genome%03d.gz' % i))
            i += 1
